#!/usr/bin/env python3
"""
build-book-c.py — /book (the demo form page) in the approved look.

The page runs in the same frame as the product pages (next/the-machine.html: head, bar,
menu, chat overlay, footer and scripts; body.hc-b + hero-b.css) with the booking content
unchanged: the title, the three points and the #bookForm mount that lead.js fills.
Run from anywhere:   python3 next/build-book-c.py     (writes next/book.html only)
"""
import pathlib, re
NEXT = pathlib.Path(__file__).resolve().parent
tpl = (NEXT / 'the-machine.html').read_text()
head = tpl[:tpl.index('<body')]
body_open_end = tpl.index('>', tpl.index('<body')) + 1
chrome = tpl[body_open_end:tpl.index('<!-- Generated by')].replace(' aria-current="page"', '')
tail = tpl[tpl.index('</main>'):]
head = re.sub(r'\n<meta name="sai-product" content="[^"]*">', '', head)
TITLE = 'Book a demo | Stagwell AI'
DESC = 'Book a demo: thirty minutes with the team who runs the product, walking through it against your brand.'
for pat, new in [
    (r'<title>[^<]*</title>', '<title>' + TITLE + '</title>'),
    (r'<meta name="description" content="[^"]*">', '<meta name="description" content="' + DESC + '">'),
    (r'<link rel="canonical" href="[^"]*">', '<link rel="canonical" href="https://stagwell.vercel.app/book">'),
    (r'<meta property="og:title" content="[^"]*">', '<meta property="og:title" content="' + TITLE + '">'),
    (r'<meta property="og:description" content="[^"]*">', '<meta property="og:description" content="' + DESC + '">'),
    (r'<meta property="og:url" content="[^"]*">', '<meta property="og:url" content="https://stagwell.vercel.app/book">'),
]:
    head, n = re.subn(pat, lambda m: new, head, count=1); assert n == 1, pat

CONTENT = '<main class="bk" id="top">\n  <section class="bk-hero">\n    <div class="pp-wrap bk__in">\n      <div class="bk__copy">\n        <h1 class="bk__title">Book a demo</h1>\n        <!-- the demo\'s own line, set as three points with icons so the side has\n             something to hold (client, 2026-09-10: "too simple… add an icon\n             something more interesting"); the words are the line\'s, nothing added -->\n        <ul class="bk__points">\n          <li><span class="bk__ic"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/></svg></span>Thirty minutes</li>\n          <li><span class="bk__ic"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="8.5" r="3"/><path d="M3.5 19c.6-3.1 2.8-5 5.5-5s4.9 1.9 5.5 5"/><circle cx="16.5" cy="9.5" r="2.4"/><path d="M15.5 14.2c2.4-.2 4.4 1.4 5 4.3"/></svg></span>With the team who runs the product</li>\n          <li><span class="bk__ic"><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="8.5"/><circle cx="12" cy="12" r="4.5"/><circle cx="12" cy="12" r="1" fill="currentColor"/></svg></span>Walked through against your brand, not a generic reel</li>\n        </ul>\n      </div>\n      <div class="bk__card">\n        <div id="bookForm" data-kind="demo" aria-label="Book a demo"></div>\n      </div>\n    </div>\n  </section>\n'

out = (head + '<body class="home pp hc-page hc-b pc-page bk-page" data-lead-cta>' + chrome +
       '<!-- Generated by next/build-book-c.py (frame: the-machine.html) — edit there, not here. -->\n' + CONTENT + tail)
assert out.count('id="bookForm"') == 1 and out.count('id="top"') == 1 and 'aria-current' not in out
(NEXT / 'book.html').write_text(out)
print('next/book.html written')
