#!/usr/bin/env python3
"""
build-solution-pages-c.py — the /s/{id} solution pages in the approved look.

Mark Penn approved homepage B (2026-09-22): Roobert, no colour. The four product
pages carry that look by hand (home-c.css / prod-c.css / hero-b.css, body.hc-b).
This script puts the thirteen /s/ pages in the same frame: the head, bar, menu,
chat overlay, closing tiles with the clients row, footer and scripts are cut from
next/the-machine.html, and the content between them is still built by
build-product-pages.py's solution_page() from data/solutions.json. Nothing in the
copy changes; the old gradient hero grounds are dropped (no colour).

Run from anywhere:   python3 next/build-solution-pages-c.py
It writes next/s/*.html only. It does not run build-product-pages.py's main(),
which would also rewrite next/index.html and next/book.html.
"""
import importlib.util
import json
import pathlib
import re

NEXT = pathlib.Path(__file__).resolve().parent
ROOT = NEXT.parent

spec = importlib.util.spec_from_file_location('bpp', NEXT / 'build-product-pages.py')
bpp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bpp)

tpl = (NEXT / 'the-machine.html').read_text()
head = tpl[:tpl.index('<body')]
body_open_end = tpl.index('>', tpl.index('<body')) + 1
chrome = tpl[body_open_end:tpl.index('<!-- Generated by')]
chrome = chrome.replace(' aria-current="page"', '')
close = tpl[tpl.index('<section class="ask-end" id="start">'):tpl.index('</main>')]
tail = tpl[tpl.index('</main>'):]
head = re.sub(r'\n<meta name="sai-product" content="[^"]*">', '', head)


def meta(h, *, title, desc, path):
    """The product page's head with this page's title, description and address."""
    for pat, new in [
        (r'<title>[^<]*</title>', f'<title>{bpp.t(title)}</title>'),
        (r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{bpp.a(desc)}">'),
        (r'<link rel="canonical" href="[^"]*">', f'<link rel="canonical" href="https://stagwell.vercel.app{path}">'),
        (r'<meta property="og:title" content="[^"]*">', f'<meta property="og:title" content="{bpp.a(title)}">'),
        (r'<meta property="og:description" content="[^"]*">', f'<meta property="og:description" content="{bpp.a(desc)}">'),
        (r'<meta property="og:url" content="[^"]*">', f'<meta property="og:url" content="https://stagwell.vercel.app{path}">'),
    ]:
        h, n = re.subn(pat, lambda m: new, h, count=1)
        assert n == 1, pat
    return h


# the picture each product carries across the site (the /products tabs' stills where the
# listing still shares one neutral picture), per the approved image set
PIC = {
    'imai': '/assets/img/tabs/imai-crowd.jpg', 'smb_platform': '/assets/img/tabs/smb-right.jpg',
    'media_machine': '/assets/img/tabs/media-machine.jpg', 'newintel': '/assets/img/tabs/newintel.jpg',
    'search_plus': '/assets/img/tabs/geopulse.jpg', 'id_graph': '/assets/img/tabs/id-graph.jpg',
}

NOTAB = ' tabindex="-1"'
# the paragraphs under each capability: DRAFTS for review (see the file's _status)
_D = json.loads((ROOT / 'data' / 'capability-drafts.json').read_text())
DRAFTS, SHORT, LOOPS = _D['products'], _D['tabs'], _D.get('loops', {})
STILL_NAMES = ('orbits', 'pulses', 'circuit', 'activity', 'globe', 'workflow', 'mosaic', 'plexus', 'world', 'converge', 'wave-dots', 'graph', 'timeline', 'radar')
VIS_ATTR = [' data-vis="screen:1"', '', ' data-vis="pic"', ' data-vis="screen:2"', '']
# a product can swap its slots (BERA: the picture under Audiences, a loop under Competitors)
VIS_BY = {'bera': [' data-vis="screen:1"', ' data-vis="pic"', '', ' data-vis="screen:2"', ''],
          'geopulse': [' data-vis="screen:1"', ' data-vis="screen:2"', ' data-vis="pic"', '', '']}  # GEOPulse: the prompt card under Prompts, the orbits loop under Simulation
ROOT_LOOPS = {'voice-squares'}
def loop_video(name):
    base = '/assets/video/lab/' + ('' if name in ROOT_LOOPS else 'loops/') + name
    return f'<video src="{base}.mp4" poster="{base}-poster.jpg" muted loop playsinline preload="metadata" aria-hidden="true"></video>'
# the tab stills: frames of the text-free motion-lab loops, a different one per tab
STILLS = [f'/assets/video/lab/loops/{k}-poster.jpg' for k in
          ('orbits', 'pulses', 'circuit', 'terrain', 'globe', 'streams', 'mosaic', 'plexus',
           'lanes', 'converge', 'charts', 'clusters', 'tunnel', 'block-rain')]
# the tabs' behaviour: without it every panel simply shows, one under another
TABS_JS = '''<script>
(function () {
  var sec = document.currentScript && document.currentScript.previousElementSibling;
  if (!sec || !sec.classList.contains('sp-tabs')) return;
  var tabs = [].slice.call(sec.querySelectorAll('.sp-tabs__tab')), panels = [].slice.call(sec.querySelectorAll('.sp-tabs__panel'));
  var bar = sec.querySelector('.sp-tabs__bar');
  function pick(i, focus) {
    tabs.forEach(function (t, n) { var on = n === i; t.classList.toggle('is-on', on); t.setAttribute('aria-selected', on ? 'true' : 'false'); t.tabIndex = on ? 0 : -1; });
    panels.forEach(function (p, n) { p.hidden = n !== i; p.classList.toggle('is-on', n === i); var v = p.querySelector('video'); if (v) { if (n === i) { var pr = v.play(); if (pr && pr.catch) pr.catch(function () {}); } else v.pause(); } });
    if (focus) tabs[i].focus();
    if (bar.scrollWidth > bar.clientWidth + 2) bar.scrollTo({ left: Math.max(0, tabs[i].offsetLeft - 20), behavior: 'smooth' });
  }
  tabs.forEach(function (t, i) {
    t.addEventListener('click', function () { pick(i); });
    t.addEventListener('keydown', function (e) {
      if (e.key === 'ArrowRight') { e.preventDefault(); pick((i + 1) % tabs.length, true); }
      if (e.key === 'ArrowLeft') { e.preventDefault(); pick((i - 1 + tabs.length) % tabs.length, true); }
    });
  });
  sec.classList.add('is-tabbed');
  pick(0);
})();
</script>'''

# solution_page() hands its parts to frame(); catch them instead of building the old frame
bpp.frame = lambda home, **kw: kw


def main():
    sols = json.loads((ROOT / 'data' / 'solutions.json').read_text())['solutions']
    by_id = {x['id']: x for x in sols}
    pics = bpp.sol_pictures()
    gen = [x for x in sols if x.get('active') and x['id'] not in bpp.SOL_OWN]
    pics.update(PIC)
    path_id = {v: k for k, v in bpp.SOL_OWN.items()}
    for n, x in enumerate(gen):
        kw = bpp.solution_page('', x, n, by_id, pics)
        body = kw['body']
        # "How it works" as tabs (the Manus solutions pages): the capabilities across the
        # top; under them one card, the capability and its paragraph on the left, a still
        # on the right. Paragraphs are DRAFTS from data/capability-drafts.json.
        more = re.search(r'<section class="pp-more">\s*<div class="pp-wrap">\s*(<div class="pp-more__head">.*?</div>)\s*'
                         r'<div class="pp-more__grid">\s*<div class="pp-more__media">(.*?)</div>\s*(<ol class="pp-steps">.*?</ol>)\s*</div>\s*'
                         r'(<p class="pp-mid">.*?</p>)\s*</div>\s*</section>', body, re.S)
        assert more, x['id']
        head_html, _media, ol_html, mid_html = more.groups()
        caps = [bpp.html.unescape(c) for c in re.findall(r'<h3>(.*?)</h3>', ol_html)]
        texts = DRAFTS[x['id']]
        assert all(c in texts for c in caps), (x['id'], [c for c in caps if c not in texts])
        sid = x['id']
        tabs = '\n'.join(
            f'      <button type="button" class="sp-tabs__tab{" is-on" if k == 0 else ""}" role="tab" id="spt-{sid}-{k}" aria-controls="spp-{sid}-{k}" '
            f'aria-selected="{"true" if k == 0 else "false"}"{"" if k == 0 else NOTAB}>{bpp.t(SHORT[x["id"]].get(c, c))}</button>' for k, c in enumerate(caps))
        panels = '\n'.join(
            f'      <article class="sp-tabs__panel{" is-on" if k == 0 else ""}" role="tabpanel" id="spp-{sid}-{k}" aria-labelledby="spt-{sid}-{k}">\n'
            f'        <div class="sp-tabs__txt"><p class="sp-tabs__n">{k + 1:02d} / {len(caps):02d}</p><h3>{bpp.t(c)}</h3><p>{bpp.t(texts[c])}</p></div>\n'
            f'        <div class="sp-tabs__pic"{VIS_BY.get(sid, VIS_ATTR)[k % 5]}>{"" if VIS_BY.get(sid, VIS_ATTR)[k % 5] else loop_video(LOOPS.get(x["id"], {}).get(c) or STILL_NAMES[(n * 4 + k) % len(STILL_NAMES)])}</div>\n'
            f'      </article>' for k, c in enumerate(caps))
        how = ('<section class="pp-more sp-tabs">\n  <div class="pp-wrap">\n'
               f'    <div class="sp-tabs__head">{head_html}</div>\n'
               f'    <div class="sp-tabs__bar" role="tablist" aria-label="What it does">\n{tabs}\n    </div>\n'
               f'    <div class="sp-tabs__panels">\n{panels}\n    </div>\n'
               f'    {mid_html}\n  </div>\n</section>\n' + TABS_JS)
        body = body[:more.start()] + how + body[more.end():]
        body = re.sub(r'<section class="pp-hero sp-hero [^"]*">', '<section class="pp-hero sp-hero">', body, count=1)
        body = re.sub(r'(data-product-site>)Visit [^<]+? website(<svg)', r'\1Visit website\2', body)
        body = re.sub(r'(data-product-site>)Get started with [^<]+?(<svg)', r'\1Get started\2', body)
        # the hero as on the reference: the words, then the product's picture wide below them
        src = pics.get(x['id'])
        if src:
            i = body.index('<section class="pp-hero sp-hero">'); j = body.index('</section>', i)
            body = body[:j] + f'  <figure class="sp-hero__pic"><img src="{src}" alt="" decoding="async" fetchpriority="high"></figure>\n' + body[j:]
        # each related product shows its own picture
        def also(mm):
            href = mm.group(1)
            pid = path_id.get(href) or href.rsplit('/', 1)[-1]
            src = pics.get(pid)
            pic = f'<span class="sp-also__pic" style="--sp-pic:url(\'{src}\')" aria-hidden="true"></span>' if src else ''
            return mm.group(0) + pic
        body = re.sub(r'<a class="sp-also__item" href="([^"]+)">', also, body)
        out = (meta(head, title=kw['title'], desc=kw['desc'], path=kw['path']) +
               f'<body class="home pp hc-page hc-b pc-page sp--{x["id"]}" data-lead-cta>' + chrome +
               '<!-- Generated by next/build-solution-pages-c.py (content: build-product-pages.py) — edit there, not here. -->\n'
               '<main id="top">\n' + body + '\n' + close + tail)
        assert out.count('id="start"') == 1 and out.count('<main id="top">') == 1 and 'aria-current' not in out
        (NEXT / 's' / f"{x['id']}.html").write_text(out)
    print(f'next/s/*.html   {len(gen)} pages: ' + ', '.join(x['id'] for x in gen))


if __name__ == '__main__':
    main()
