#!/usr/bin/env python3
"""
build-solution-pages-c.py — the /s/{id} solution pages in the approved look.

Mark Penn approved homepage B (2026-09-22): Roobert, no colour. The four product
pages carry that look by hand (home-c.css / prod-c.css / hero-b.css, body.hc-b).
This script puts the thirteen /s/ pages in the same frame: the head, bar, menu,
chat overlay, closing tiles with the clients row, footer and scripts are cut from
next/the-machine.html, and the content between them is still built by
build-product-pages.py's solution_page() from data/solutions.json. Nothing in the
copy changes; the old gradient hero grounds are dropped (no colour).

Run from anywhere:   python3 next/build-solution-pages-c.py
It writes next/s/*.html only. It does not run build-product-pages.py's main(),
which would also rewrite next/index.html and next/book.html.
"""
import importlib.util
import json
import pathlib
import re

NEXT = pathlib.Path(__file__).resolve().parent
ROOT = NEXT.parent

spec = importlib.util.spec_from_file_location('bpp', NEXT / 'build-product-pages.py')
bpp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bpp)

tpl = (NEXT / 'the-machine.html').read_text()
head = tpl[:tpl.index('<body')]
body_open_end = tpl.index('>', tpl.index('<body')) + 1
chrome = tpl[body_open_end:tpl.index('<!-- Generated by')]
chrome = chrome.replace(' aria-current="page"', '')
close = tpl[tpl.index('<section class="ask-end" id="start">'):tpl.index('</main>')]
tail = tpl[tpl.index('</main>'):]
head = re.sub(r'\n<meta name="sai-product" content="[^"]*">', '', head)


def meta(h, *, title, desc, path):
    """The product page's head with this page's title, description and address."""
    for pat, new in [
        (r'<title>[^<]*</title>', f'<title>{bpp.t(title)}</title>'),
        (r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{bpp.a(desc)}">'),
        (r'<link rel="canonical" href="[^"]*">', f'<link rel="canonical" href="https://stagwell.vercel.app{path}">'),
        (r'<meta property="og:title" content="[^"]*">', f'<meta property="og:title" content="{bpp.a(title)}">'),
        (r'<meta property="og:description" content="[^"]*">', f'<meta property="og:description" content="{bpp.a(desc)}">'),
        (r'<meta property="og:url" content="[^"]*">', f'<meta property="og:url" content="https://stagwell.vercel.app{path}">'),
    ]:
        h, n = re.subn(pat, lambda m: new, h, count=1)
        assert n == 1, pat
    return h


# the picture each product carries across the site (the /products tabs' stills where the
# listing still shares one neutral picture), per the approved image set
PIC = {
    'imai': '/assets/img/tabs/imai-crowd.jpg', 'smb_platform': '/assets/img/tabs/smb-right.jpg',
    'media_machine': '/assets/img/tabs/media-machine.jpg', 'newintel': '/assets/img/tabs/newintel.jpg',
    'search_plus': '/assets/img/tabs/geopulse.jpg', 'id_graph': '/assets/img/tabs/id-graph.jpg',
}

# solution_page() hands its parts to frame(); catch them instead of building the old frame
bpp.frame = lambda home, **kw: kw


def main():
    sols = json.loads((ROOT / 'data' / 'solutions.json').read_text())['solutions']
    by_id = {x['id']: x for x in sols}
    pics = bpp.sol_pictures()
    gen = [x for x in sols if x.get('active') and x['id'] not in bpp.SOL_OWN]
    pics.update(PIC)
    path_id = {v: k for k, v in bpp.SOL_OWN.items()}
    for n, x in enumerate(gen):
        kw = bpp.solution_page('', x, n, by_id, pics)
        body = kw['body']
        # "How it works" in two columns: the product's square picture on the left; the
        # heading and the capabilities as a numbered list on the right (no tabs: there is
        # one picture and no step descriptions to rotate through)
        more = re.search(r'<section class="pp-more">\s*<div class="pp-wrap">\s*(<div class="pp-more__head">.*?</div>)\s*'
                         r'<div class="pp-more__grid">\s*<div class="pp-more__media">(.*?)</div>\s*(<ol class="pp-steps">.*?</ol>)\s*</div>\s*'
                         r'(<p class="pp-mid">.*?</p>)\s*</div>\s*</section>', body, re.S)
        assert more, x['id']
        head_html, media_html, ol_html, mid_html = more.groups()
        ol_html = ol_html.replace('<ol class="pp-steps">', '<ol class="pp-steps sp-caps">', 1)
        how = ('<section class="pp-more sp-how">\n  <div class="pp-wrap sp-how__in">\n'
               f'    <div class="sp-how__pic">{media_html}</div>\n'
               f'    <div class="sp-how__txt">\n      {head_html}\n      {ol_html}\n      {mid_html}\n    </div>\n'
               '  </div>\n</section>')
        body = body[:more.start()] + how + body[more.end():]
        body = re.sub(r'<section class="pp-hero sp-hero [^"]*">', '<section class="pp-hero sp-hero">', body, count=1)
        # each related product shows its own picture
        def also(mm):
            href = mm.group(1)
            pid = path_id.get(href) or href.rsplit('/', 1)[-1]
            src = pics.get(pid)
            pic = f'<span class="sp-also__pic" style="--sp-pic:url(\'{src}\')" aria-hidden="true"></span>' if src else ''
            return mm.group(0) + pic
        body = re.sub(r'<a class="sp-also__item" href="([^"]+)">', also, body)
        out = (meta(head, title=kw['title'], desc=kw['desc'], path=kw['path']) +
               f'<body class="home pp hc-page hc-b pc-page sp--{x["id"]}" data-lead-cta>' + chrome +
               '<!-- Generated by next/build-solution-pages-c.py (content: build-product-pages.py) — edit there, not here. -->\n'
               '<main id="top">\n' + body + '\n' + close + tail)
        assert out.count('id="start"') == 1 and out.count('<main id="top">') == 1 and 'aria-current' not in out
        (NEXT / 's' / f"{x['id']}.html").write_text(out)
    print(f'next/s/*.html   {len(gen)} pages: ' + ', '.join(x['id'] for x in gen))


if __name__ == '__main__':
    main()
