#!/usr/bin/env python3
"""
build-solution-pages-c.py — the /s/{id} solution pages in the approved look.

Mark Penn approved homepage B (2026-09-22): Roobert, no colour. The four product
pages carry that look by hand (home-c.css / prod-c.css / hero-b.css, body.hc-b).
This script puts the thirteen /s/ pages in the same frame: the head, bar, menu,
chat overlay, closing tiles with the clients row, footer and scripts are cut from
next/the-machine.html, and the content between them is still built by
build-product-pages.py's solution_page() from data/solutions.json. Nothing in the
copy changes; the old gradient hero grounds are dropped (no colour).

Run from anywhere:   python3 next/build-solution-pages-c.py
It writes next/s/*.html only. It does not run build-product-pages.py's main(),
which would also rewrite next/index.html and next/book.html.
"""
import importlib.util
import json
import pathlib
import re

NEXT = pathlib.Path(__file__).resolve().parent
ROOT = NEXT.parent

spec = importlib.util.spec_from_file_location('bpp', NEXT / 'build-product-pages.py')
bpp = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bpp)

tpl = (NEXT / 'the-machine.html').read_text()
head = tpl[:tpl.index('<body')]
body_open_end = tpl.index('>', tpl.index('<body')) + 1
chrome = tpl[body_open_end:tpl.index('<!-- Generated by')]
chrome = chrome.replace(' aria-current="page"', '')
close = tpl[tpl.index('<section class="ask-end" id="start">'):tpl.index('</main>')]
tail = tpl[tpl.index('</main>'):]
head = re.sub(r'\n<meta name="sai-product" content="[^"]*">', '', head)


def meta(h, *, title, desc, path):
    """The product page's head with this page's title, description and address."""
    for pat, new in [
        (r'<title>[^<]*</title>', f'<title>{bpp.t(title)}</title>'),
        (r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{bpp.a(desc)}">'),
        (r'<link rel="canonical" href="[^"]*">', f'<link rel="canonical" href="https://stagwell.vercel.app{path}">'),
        (r'<meta property="og:title" content="[^"]*">', f'<meta property="og:title" content="{bpp.a(title)}">'),
        (r'<meta property="og:description" content="[^"]*">', f'<meta property="og:description" content="{bpp.a(desc)}">'),
        (r'<meta property="og:url" content="[^"]*">', f'<meta property="og:url" content="https://stagwell.vercel.app{path}">'),
    ]:
        h, n = re.subn(pat, lambda m: new, h, count=1)
        assert n == 1, pat
    return h


# solution_page() hands its parts to frame(); catch them instead of building the old frame
bpp.frame = lambda home, **kw: kw


def main():
    sols = json.loads((ROOT / 'data' / 'solutions.json').read_text())['solutions']
    by_id = {x['id']: x for x in sols}
    pics = bpp.sol_pictures()
    gen = [x for x in sols if x.get('active') and x['id'] not in bpp.SOL_OWN]
    for n, x in enumerate(gen):
        kw = bpp.solution_page('', x, n, by_id, pics)
        body = re.sub(r'<section class="pp-hero sp-hero [^"]*">', '<section class="pp-hero sp-hero">', kw['body'], count=1)
        out = (meta(head, title=kw['title'], desc=kw['desc'], path=kw['path']) +
               f'<body class="home pp hc-page hc-b pc-page sp--{x["id"]}" data-lead-cta>' + chrome +
               '<!-- Generated by next/build-solution-pages-c.py (content: build-product-pages.py) — edit there, not here. -->\n'
               '<main id="top">\n' + body + '\n' + close + tail)
        assert out.count('id="start"') == 1 and out.count('<main id="top">') == 1 and 'aria-current' not in out
        (NEXT / 's' / f"{x['id']}.html").write_text(out)
    print(f'next/s/*.html   {len(gen)} pages: ' + ', '.join(x['id'] for x in gen))


if __name__ == '__main__':
    main()
